name: Build

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'

    - name: Checkout project source code
      uses: actions/checkout@v3

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v ./...
